#ifndef CONSTANTS_H_INCLUDED
#define CONSTANTS_H_INCLUDED

#define DB_NAME "katalog.db"
#define IMAGE_DIR "../images"
#define AUDIO_DIR "../audio"
#define PORTRAITS_DIR "../portraits"

enum viewsEnum { MAINMENU, OVERVIEW, WORLDVIEW };
enum swipeGesturesEnum { SWIPE_LEFT, SWIPE_RIGHT, SWIPE_UP, SWIPE_DOWN };
enum zoomLevelEnum { ZOOM_IN, ZOOM_OUT, ZOOM_RESET };
enum fachbereichEnum {FACHBEREICH_ALL,FACHBEREICH_AD,FACHBEREICH_CICD,FACHBEREICH_DM,FACHBEREICH_FG,FACHBEREICH_GD,FACHBEREICH_IAID,FACHBEREICH_LD,FACHBEREICH_MG,FACHBEREICH_PD};

#endif // CONSTANTS_H_INCLUDED
